#!/bin/bash

#PBS -N qchem_b3lyp
#PBS -q ishared
#PBS -l nodes=1:ppn=1
#PBS -l walltime=144:00:00
#PBS -j oe
#PBS -l qos=low

module purge
module load intel/2013.0
module load qchem/dlambrecht/4.1-trunk.20130919.omp.ccman2

cp $PBS_O_WORKDIR/b3lyp.in  $LOCAL
cd $LOCAL

run_on_exit() {
    set -v
    cp $LOCAL/* $PBS_O_WORKDIR
}

trap run_on_exit EXIT

`which qchem` b3lyp.in >& $PBS_O_WORKDIR/b3lyp.out

